name: Reusable Log Check


on:
  workflow_call:
    inputs:
      log_level:
       required: true
       type: string

jobs:
  log-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make log report executable
        run: chmod u+x log-report.sh

      - name: Run log report
        run: |
          report="$(./log-report.sh app.log "${{ inputs.log_level }}")"
          printf '%s/n' "$report"

          {
           echo "## Log Report"
           echo
           echo "**Selected level:** ${{ inputs.log_level }}"
           echo
           printf '%s/n' "$report"
          } >> "$GITHUB_STEP_SUMMARY"


#    This section is when you only want to display in the Log summary
#         {
 #           echo "## Log Report"
  #          echo
   #         echo "**Selected level:** ${{ inputs.log_level }}
   #         echo
    #        echo "Report output:"
     #       ./log-report.sh app.log "${{ inputs.log_level }}
     #     } >> "$GITHUB_STEP_SUMMARY"
